/**
 * Seed tool.
 *   npx tsx scripts/seed.ts sql   → writes supabase/seed.sql (idempotent upserts) from src/data/seed/*
 *   npx tsx scripts/seed.ts push  → upserts the same data into the Supabase project in .env.local (service role)
 *   npx tsx scripts/seed.ts       → both
 */
import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { createClient } from "@supabase/supabase-js";
import { categories } from "../src/data/seed/categories";
import { districts } from "../src/data/seed/districts";
import { universities } from "../src/data/seed/universities";
import { programs } from "../src/data/seed/programs";
import { requirements } from "../src/data/seed/requirements";
import { scholarships, rankings } from "../src/data/seed/scholarships";
import { services, stories, posts, faqs, siteSettings } from "../src/data/seed/content";

type Row = Record<string, unknown>;

const TABLES: { name: string; rows: Row[]; conflict: string }[] = [
  { name: "categories", rows: categories as unknown as Row[], conflict: "id" },
  { name: "districts", rows: districts as unknown as Row[], conflict: "id" },
  { name: "universities", rows: universities as unknown as Row[], conflict: "id" },
  { name: "programs", rows: programs as unknown as Row[], conflict: "id" },
  { name: "admission_requirements", rows: requirements as unknown as Row[], conflict: "id" },
  { name: "scholarships", rows: scholarships as unknown as Row[], conflict: "id" },
  { name: "rankings", rows: rankings as unknown as Row[], conflict: "id" },
  { name: "services", rows: services as unknown as Row[], conflict: "id" },
  { name: "stories", rows: stories as unknown as Row[], conflict: "id" },
  { name: "posts", rows: posts as unknown as Row[], conflict: "id" },
  { name: "faqs", rows: faqs as unknown as Row[], conflict: "id" },
  {
    name: "site_settings",
    rows: Object.entries(siteSettings).map(([key, value]) => ({ key, value })),
    conflict: "key",
  },
];

/* ───────── SQL generation ───────── */
const lit = (v: unknown): string => {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "true" : "false";
  if (Array.isArray(v) && v.every((x) => typeof x === "string")) return `array[${v.map((x) => lit(x)).join(",")}]::text[]`;
  if (typeof v === "object") return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
};
const q = (col: string) => (col === "order" ? `"order"` : col);

function toSql(): string {
  const out: string[] = ["-- GENERATED by scripts/seed.ts — do not edit by hand. Re-run `npx tsx scripts/seed.ts sql`.", "begin;"];
  for (const t of TABLES) {
    if (!t.rows.length) continue;
    const cols = Array.from(new Set(t.rows.flatMap((r) => Object.keys(r))));
    out.push(`\n-- ${t.name} (${t.rows.length})`);
    for (const r of t.rows) {
      const vals = cols.map((c) => lit(r[c]));
      const updates = cols.filter((c) => c !== t.conflict).map((c) => `${q(c)} = excluded.${q(c)}`).join(", ");
      out.push(`insert into public.${t.name} (${cols.map(q).join(", ")}) values (${vals.join(", ")}) on conflict (${t.conflict}) do update set ${updates};`);
    }
  }
  out.push("commit;");
  return out.join("\n");
}

/* ───────── Push via service role ───────── */
function loadEnv() {
  if (!existsSync(".env.local")) return;
  for (const line of readFileSync(".env.local", "utf8").split(/\r?\n/)) {
    const m = line.match(/^([A-Z0-9_]+)=(.*)$/);
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2];
  }
}

async function push() {
  loadEnv();
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) throw new Error("NEXT_PUBLIC_SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY missing in .env.local");
  const sb = createClient(url, key, { auth: { persistSession: false } });
  for (const t of TABLES) {
    const chunk = 200;
    for (let i = 0; i < t.rows.length; i += chunk) {
      const { error } = await sb.from(t.name).upsert(t.rows.slice(i, i + chunk), { onConflict: t.conflict });
      if (error) throw new Error(`${t.name}: ${error.message}`);
    }
    console.log(`✓ ${t.name}: ${t.rows.length} rows`);
  }
}

const mode = process.argv[2] ?? "both";
if (mode === "sql" || mode === "both") {
  writeFileSync("supabase/seed.sql", toSql());
  console.log("✓ supabase/seed.sql written");
}
if (mode === "push" || mode === "both") {
  push().catch((e) => {
    console.error("✗ push failed:", e.message);
    process.exit(1);
  });
}
